import 'package:flutter/material.dart';

extension AppTranslator on BuildContext {
  String tr(String key) {
    final locale = Localizations.localeOf(this).languageCode;
    return _translations[locale]?[key] ?? _translations['es']?[key] ?? key;
  }
}

const Map<String, Map<String, String>> _translations = {
  'es': {
    // General
    'cancel': 'Cancelar',
    'confirm': 'Confirmar',
    'currency': 'Moneda',
    'currency_setup_title': 'Elige tu moneda',
    'currency_setup_subtitle': 'Puedes cambiarla después en configuración.',
    'currency_setup_confirm': 'CONFIRMAR',
    'exitWithoutSaving': '¿Salir sin guardar?',
    'unsavedAmount': 'Tienes un monto sin confirmar.',
    'unsavedChanges': 'Tienes cambios sin guardar.',
    'genericError': 'Ocurrió un error. Intenta de nuevo.',
    'language_setup_title': 'Elige tu idioma',
    'language_setup_subtitle': 'Puedes cambiarlo después en Configuración.',
    'language_setup_next': 'SIGUIENTE',
    'saving': 'Ahorro',
    'expense': 'Gasto',
    'available': 'Disponible',
    'continue': 'Continuar',
    'goal': 'Meta',
    'no_results': 'Sin resultados.',
    'view_all': 'Ver todos',
    'envelopes': 'sobres',
    'error_enter_amount': 'Ingresa un monto.',
    'error_invalid_amount': 'El monto no es válido.',
    'error_insufficient_funds': 'No tienes suficiente dinero en ese sobre. Disponible:',

    // Home
    'balanceGeneral': 'BALANCE GENERAL',
    'assignedToExpenses': 'DINERO ASIGNADO A GASTOS',
	'assigned_to_expenses': 'Destinado a gastos',
    'savings': 'MIS AHORROS',
	'savingsM': 'Mis ahorros',
    'default_user': 'Usuario',
    'hello': 'Hola',
    'general_balance': 'Balance general',
    'available_balance_subtitle': 'Saldo disponible',
    'available_balance_title': 'Balance disponible',
    'money_assigned_to_expenses': 'Dinero asignado a gastos',
    'general_balance_upper': 'BALANCE GENERAL',
    'available_income': 'Ingresos disponibles',
    'in_savings': 'En ahorros',
    'available_balance_upper': 'BALANCE DISPONIBLE',
    'top_envelopes': 'Top sobres con más dinero',
    'no_expense_envelopes': 'Sin sobres de gasto.',
    'and_word': 'y',
    'more_envelopes': 'sobres más',
    'tap_to_continue': 'Toca para continuar',
    'goal_reached': 'Meta alcanzada',
    'tap_to_use': 'Tocar para usar →',

    // Navegación
    'income': 'INGRESO',
    'destinar': 'DESTINAR',
    'categories': 'CATEGORÍAS',
    'reparto': 'REPARTO',
    'history': 'HISTORIAL',
	'expensesM': 'GASTOS',

    // Settings & Perfil y Auth
    'sectionAccount': 'CUENTA',
    'sectionAppearance': 'APARIENCIA',
    'sectionBenefits': 'BENEFICIOS',
    'sectionAbout': 'ACERCA DE',
    'sectionSession': 'SESIÓN',
    'settings': 'Ajustes',
    'profile': 'Perfil',
    'darkMode': 'Modo oscuro',
    'themeSystem': 'Sistema',
    'themeLight': 'Claro',
    'themeDark': 'Oscuro',
    'language': 'Idioma',
    'donate': 'Apoya al desarrollador',
    'adFreeMode': 'Sin anuncios por 6 horas',
    'premium': 'Premium',
    'logout': 'Cerrar sesión',
    'deleteAccount': 'Eliminar cuenta',
    'logoutConfirm': '¿Seguro que quieres cerrar sesión?',
    'deleteAccountConfirm': 'Esta acción es irreversible. Se borrarán todos tus datos y perderás tu beneficio Premium si lo adquiriste. ¿Deseas continuar?',
    'aboutApp': 'Acerca de Hivefi',
    'appVersion': 'Versión 2.0.0',
    'madeBy': 'Desarrollado por',
    'saveName': 'GUARDAR NOMBRE',
    'nameEmpty': 'El nombre no puede estar vacío.',
    'nameUpdated': 'Nombre actualizado correctamente.',
    'changePassword': 'Cambiar contraseña',
    'changePasswordDesc': 'Te enviaremos un correo a tu dirección registrada con un enlace para cambiar tu contraseña.',
    'sendResetEmail': 'ENVIAR CORREO DE RESTABLECIMIENTO',
    'resetSent': 'Correo enviado. Revisa tu bandeja de entrada.',
    'email': 'CORREO ELECTRÓNICO',
    'emailHint': 'ejemplo@correo.com',
    'password': 'CONTRASEÑA',
    'login': 'INICIAR SESIÓN',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'noAccount': '¿No tienes cuenta?',
    'register': 'Registrate',
    'tagline': 'Tus finanzas organizadas.',
    'name': 'NOMBRE',
    'nameHint': 'Tu nombre',
    'confirmPassword': 'CONFIRMAR CONTRASEÑA',
    'createAccount': 'CREAR CUENTA',
    'alreadyHaveAccount': '¿Ya tienes cuenta?',
    'loginLink': 'Iniciá sesión',
    'passwordMismatch': 'Las contraseñas no coinciden.',
    'passwordTooShort': 'La contraseña debe tener al menos 6 caracteres.',
	'apoyoTitulo': 'Apoya al desarrollador',
'apoyoSubtitulo': 'Hive-Fi es desarrollado por una sola persona. Tu apoyo hace posible seguir mejorando la app.',
'apoyoCafe': 'Un café',
'apoyoCafeDesc': 'El combustible del desarrollo.',
'apoyoComida': 'Una comida',
'apoyoComidaDesc': 'Para seguir construyendo con energía.',
'apoyoBanquete': 'El banquete completo',
'apoyoBanqueteDesc': 'Tu apoyo más generoso.',
'apoyoNota': 'Las contribuciones no otorgan beneficios adicionales en la app.',
'apoyoError': 'No se pudo procesar el pago. Intenta de nuevo.',
'rateApp': 'Calificar aplicación',
  'shareApp': 'Compartir con amigos',
  'shareMessage': 'Descarga Hivefi desde la Play Store:',


    // Premium
    'premiumSubtitulo': 'Pago único. Sin suscripciones.',
    'premiumBeneficio1': 'Modo oscuro',
    'premiumBeneficio1Desc': 'Cuida tus ojos con el tema oscuro.',
    'premiumBeneficio2': 'Categorías ilimitadas',
    'premiumBeneficio2Desc': 'Crea todos los sobres que necesitas.',
    'premiumBeneficio3': 'Sin anuncios para siempre',
    'premiumBeneficio3Desc': 'Experiencia limpia sin interrupciones.',
    'premiumPagoUnico': 'Pago único — acceso de por vida',
    'premiumActivar': 'Activar Premium',
    'premiumActivo': 'Premium activo',
    'premiumRestaurar': 'Restaurar compra anterior',
    'premiumRestaurado': 'Compra restaurada correctamente.',
    'premiumErrorCompra': 'No se pudo completar la compra. Intenta de nuevo.',

    // Categorías y Sobres
    'newCategory': 'NUEVA\nCATEGORÍA',
    'categories_title': 'Categorías',
    'your_envelopes': 'Tus sobres',
    'organize_your_money': 'Organiza tu dinero en categorías.',
    'incomes': 'Ingresos',
    'expenses': 'Gastos',
    'no_categories_yet': 'Sin categorías aún.',
    'tap_plus_to_create': 'Toca + para crear una.',
    'search_category': 'Buscar categoría...',
    'cannot_delete_category_with_money': 'No se puede eliminar: la categoría tiene dinero asignado.',
    'use_savings': 'Usar ahorro',
    'delete_category': 'Eliminar categoría',
    'confirm_delete_category': '¿Seguro que quieres eliminar esta categoría?',
    'edit_name': 'Editar nombre',
    'new_name': 'Nuevo nombre',
    'save': 'Guardar',
    'where_to_send_savings': '¿A qué sobre de gasto quieres enviar el dinero?',
    'no_expense_categories': 'No tienes categorías de gasto creadas.',
    'select_envelope': 'Selecciona un sobre',
    'category_already_exists': 'Ya existe una categoría con este nombre.',
    'error_creating_category': 'Error al crear la categoría.',
    'type': 'Tipo',
    'example_category_name': 'Ej: Sueldo, Comida, Viaje',
    'savings_goal_optional': 'Meta de ahorro (opcional)',
    'example_amount': 'Ej: 100',
    'create_category': 'CREAR CATEGORÍA',
    'new_category': 'Nueva categoria',
	'incomem': 'Ingreso',

    // Ingresos
    'registerIncome': 'REGISTRAR\nINGRESO',
    'whereMoneyEnters': '¿A QUÉ CUENTA ENTRA EL DINERO?',
    'incomeAmount': 'MONTO DEL INGRESO',
    'confirmIncome': 'CONFIRMAR ENTRADA',
    'incomeRegistered': 'Ingreso registrado correctamente.',
    'recentHistory': 'HISTORIAL RECIENTE',
    'noIncomeCategories': 'Sin categorías de ingreso.',
    'createInCategoriesFirst': 'Crea una en Categorías primero.',
    'title_incomes': 'Ingresos',
    'income_envelopes_title': 'Sobres de ingreso',
    'income_envelopes_desc': 'Dinero disponible para distribuir.',
    'search_category_hint': 'Buscar categoría...',
    'no_movements_yet': 'Sin movimientos aún.',
    'cannot_edit_destined_income': 'No se puede editar: este ingreso ya fue destinado.',
    'register_income_title': 'Registrar ingreso',
    'which_account_money_enters': '¿A qué cuenta entra el dinero?',
    'loading_categories': 'Cargando categorías...',
    'select_category_hint': 'Selecciona una categoría',
    'income_amount_label': 'Monto del ingreso',
    'error_select_category': 'Selecciona una categoría.',
    'error_registering_income': 'Error al registrar el ingreso.',
    'confirm_income': 'Confirmar ingreso',
    'edit_income_title': 'Editar ingreso',
    'new_amount_label': 'Nuevo monto',
    'error_editing_income': 'Error al editar el ingreso.',
    'save_changes': 'Guardar cambios',

    // Gastos
    'registerExpense': 'REGISTRAR\nGASTO',
    'whereMoneyLeaves': '¿DE QUÉ SOBRE SALE EL DINERO?',
    'expenseAmount': 'MONTO A GASTAR',
    'confirmExpense': 'CONFIRMAR GASTO',
    'expenseRegistered': 'Gasto registrado correctamente.',
    'notEnoughFunds': 'No tienes suficiente dinero en este sobre.',
    'title_expenses': 'Gastos',
    'expense_envelopes_title': 'Sobres de gasto',
    'expense_envelopes_desc': 'Solo puedes gastar dinero que fue destinado.',
    'search_envelope_hint': 'Buscar sobre',
    'no_funds': 'Sin fondos',
    'delete_expense_title': 'Eliminar gasto',
    'delete_expense_desc_1': 'Se eliminará el gasto y se devolverán',
    'delete_expense_desc_2': 'al sobre.',
    'cancel_button': 'Cancelar',
    'delete_button': 'Eliminar',
    'error_select_envelope': 'Selecciona un sobre.',
    'error_registering_expense': 'Error al registrar el gasto.',
    'register_expense_title': 'Registrar gasto',
    'from_which_envelope': '¿De qué sobre sale el dinero?',
    'no_envelopes_available': 'No tienes sobres con dinero disponible. Primero destiná dinero.',
    'select_envelope_hint': 'Selecciona un sobre',
    'available_label': 'Disponible',
    'amount_to_spend_label': 'Monto a gastar',
    'confirm_expense': 'Confirmar gasto',
    'error_amount_exceeds_limit': 'El monto supera el límite del sobre. Máximo:',
    'error_editing_expense': 'Error al editar el gasto.',
    'edit_expense_title': 'Editar gasto',
    'envelope_label': 'Sobre',
    'which_account_money_exits': '¿De qué cuenta sale el dinero?',
	'expense_amount_label': 'Monto del gasto',
	'delete': 'Eliminar',
'delete_expense_confirm': '¿Eliminar este gasto? El monto se devolverá al sobre.',

    // Destinar y Reparto
    'allocateMoney': 'DESTINAR\nDINERO',
    'allocateSubtitle': 'Distribuye tus ingresos en sobres de gasto o ahorro.',
    'whereMoneyFrom': '¿DE DÓNDE SALE EL DINERO?',
    'whereMoneyTo': '¿A QUÉ SOBRE LO ASIGNAS?',
    'amountToAllocate': 'MONTO A DESTINAR',
    'confirmAllocate': 'CONFIRMAR DESTINO',
    'allocateRegistered': 'Dinero destinado correctamente.',
    'sameAccountError': 'El origen y destino no pueden ser iguales.',
    'notEnoughFundsGeneral': 'No tienes suficiente dinero disponible.',
    'savingsLabel': 'AHORRO',
    'allocate_money_title': 'Destinar dinero',
    'no_available_money': 'Sin dinero disponible',
    'register_income_first': 'Primero registra un ingreso para poder destinar dinero.',
    'distribute_your_money': 'Distribuye tu dinero',
    'assign_money_to_envelopes': 'Asigna tu dinero a sobres de gasto o ahorro.',
    'all_incomes': 'Todos los ingresos',
    'expense_envelopes': 'Sobres de gasto',
    'savings_envelopes': 'Sobres de ahorro',
    'search_envelope': 'Buscar sobre',
    'enter_an_amount': 'Ingresa un monto.',
    'invalid_amount': 'El monto no es válido.',
    'insufficient_income': 'No tienes suficiente en el ingreso. Disponible:',
    'error_editing_destination': 'Error al editar el destino.',
    'edit_destination': 'Editar destino',
    'new_amount': 'Nuevo monto',
    'allocate_money': 'Destinar dinero',
    'where_does_money_come_from': '¿De dónde sale el dinero?',
    'no_incomes_available': 'No tienes ingresos con dinero disponible.',
    'select_income': 'Selecciona el ingreso',
    'which_envelope_assign': '¿A qué sobre lo asignas?',
    'no_expense_savings_envelopes': 'No tienes sobres de gasto ni ahorro creados.',
    'select_destination': 'Selecciona el destino',
    'amount_to_allocate': 'Monto a destinar',
    'select_source_of_money': 'Selecciona de dónde sale el dinero.',
    'select_destination_of_money': 'Selecciona a dónde va el dinero.',
    'insufficient_money': 'No tienes suficiente dinero. Disponible:',
    'error_allocating_money': 'Error al destinar el dinero.',
    'confirm_allocation': 'Confirmar destino',
    'reparto_title': 'Reparto',
    'no_envelopes_created': 'Sin sobres creados',
    'create_categories_first': 'Crea categorías de gasto o ahorro primero.',
    'move_money_between_envelopes': 'Mover dinero entre sobres',
    'reassign_money_desc': 'Reasigna dinero entre tus sobres de gasto y ahorro.',
    'savings_envelopes_title': 'Sobres de ahorro',
    'in_progress': 'En progreso',
    'are_you_sure': '¿Estás seguro?',
    'saving_meta_warning_part1': 'Este sobre de ahorro aún no alcanzó su meta. Si mueves',
    'saving_meta_warning_part2': 'reducirás el dinero destinado a ese ahorro. ¿Deseas continuar?',
    'error_performing_split': 'Error al realizar el reparto.',
    'move_money_title': 'Mover dinero',
    'reassign_money_short_desc': 'Reasigna dinero entre tus sobres.',
    'from_which_envelope_question': '¿De qué sobre sacás el dinero?',
    'select_source_hint': 'Selecciona el origen',
    'to_which_envelope_question': '¿A qué sobre lo envias?',
    'select_destination_hint': 'Selecciona el destino',
    'amount_to_move': 'Monto a mover',
    'confirm_split_button': 'Confirmar reparto',

    // Historial y Tooltips
    'historialTitle': 'ANÁLISIS\nDE CUENTA',
    'filterByMonth': 'FILTRAR POR MES',
    'year': 'AÑO',
    'tabSummary': 'RESUMEN',
    'tabIncome': 'INGRESOS',
    'tabExpenses': 'GASTOS',
    'balance': 'SALDO',
    'noMovements': 'Sin movimientos.',
    'editMovement': 'Editar movimiento',
    'cancelMovement': 'Anular movimiento',
    'longPressHint': 'Manten presionado un movimiento para editarlo o anularlo.',
    'adFreeActivated': 'Sin anuncios por 6 horas. ¡Disfrutalo!',
    'adFreeError': 'No se pudo activar. Intenta de nuevo.',
    'historialAppBar': 'Historial',
    'resumenIngresos': 'Ingresos',
    'resumenGastos': 'Gastos',
    'resumenSaldo': 'Saldo',
    'donutTitulo': '¿En qué gasté más?',
    'donutSinGastos': 'Sin gastos registrados este mes.',
    'otrosLabel': 'Otros',
    'sinNombre': 'Sin nombre',
    'tendenciaTitulo': 'Ingresos vs Gastos',
    'topSobresTitulo': 'Sobres más activos',
    'topSobresSinGastos': 'Sin gastos registrados este mes.',
    'progresoAhorrosTitulo': 'Progreso de ahorros',
    'movimientosTitulo': 'Movimientos',
    'sinMovimientosMes': 'Sin movimientos este mes.',
    'tooltip_ingreso': 'Aquí registras el dinero que recibes. Selecciona una cuenta y confirma el monto.',
    'tooltip_gasto': 'Aquí registras tus gastos. El dinero se descuenta del sobre seleccionado.',
    'tooltip_destinar': 'Mueve dinero de tus ingresos hacia un sobre de gasto o ahorro.',
    'tooltip_reparto': 'Redistribute dinero entre tus sobres sin necesidad de un ingreso nuevo.',
    'tooltip_categorias': 'Tus sobres de presupuesto. Puedes crear sobres de ingreso, gasto y ahorro.',
    'tooltip_historial': 'Consulta y analiza todos tus movimientos filtrados por mes.',
    'emptyAmount': 'Ingresa un monto.',
    'invalidAmount': 'El monto no es válido.',
	'deMeta': 'de {meta}',
	'mes_1': 'Enero',
'mes_2': 'Febrero',
'mes_3': 'Marzo',
'mes_4': 'Abril',
'mes_5': 'Mayo',
'mes_6': 'Junio',
'mes_7': 'Julio',
'mes_8': 'Agosto',
'mes_9': 'Septiembre',
'mes_10': 'Octubre',
'mes_11': 'Noviembre',
'mes_12': 'Diciembre',

  },
  'en': {
    // General
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'currency': 'Currency',
    'currency_setup_title': 'Choose your currency',
    'currency_setup_subtitle': 'You can change it later in Settings.',
    'currency_setup_confirm': 'CONFIRM',
    'exitWithoutSaving': 'Exit without saving?',
    'unsavedAmount': 'You have an unconfirmed amount.',
    'unsavedChanges': 'You have unsaved changes.',
    'genericError': 'An error occurred. Please try again.',
    'language_setup_title': 'Choose your language',
    'language_setup_subtitle': 'You can change it later in Settings.',
    'language_setup_next': 'NEXT',
    'saving': 'Saving',
    'expense': 'Expense',
    'available': 'Available',
    'continue': 'Continue',
    'goal': 'Goal',
    'no_results': 'No results.',
    'view_all': 'View all',
    'envelopes': 'envelopes',
    'error_enter_amount': 'Enter an amount.',
    'error_invalid_amount': 'Invalid amount.',
    'error_insufficient_funds': 'Not enough money in that envelope. Available:',

    // Home
    'balanceGeneral': 'GENERAL BALANCE',
    'assignedToExpenses': 'MONEY ASSIGNED TO EXPENSES',
	'assigned_to_expenses': 'Assigned to expenses',
    'savings': 'MY SAVINGS',
	'savingsM': 'My savings',
    'default_user': 'User',
    'hello': 'Hello',
    'general_balance': 'General balance',
    'available_balance_subtitle': 'Available balance',
    'available_balance_title': 'Available balance',
    'money_assigned_to_expenses': 'Money assigned to expenses',
    'general_balance_upper': 'GENERAL BALANCE',
    'available_income': 'Available income',
    'in_savings': 'In savings',
    'available_balance_upper': 'AVAILABLE BALANCE',
    'top_envelopes': 'Top envelopes with more money',
    'no_expense_envelopes': 'No expense envelopes.',
    'and_word': 'and',
    'more_envelopes': 'more envelopes',
    'tap_to_continue': 'Tap to continue',
    'goal_reached': 'Goal reached',
    'tap_to_use': 'Tap to use →',

    // Navegación
    'income': 'INCOME',
    'destinar': 'ALLOCATE',
    'categories': 'CATEGORIES',
    'reparto': 'SPLIT',
    'history': 'HISTORY',
	'expensesM': 'EXPENSES',

    // Settings
    'sectionAccount': 'ACCOUNT',
    'sectionAppearance': 'APPEARANCE',
    'sectionBenefits': 'BENEFITS',
    'sectionAbout': 'ABOUT',
    'sectionSession': 'SESSION',
    'settings': 'Settings',
    'profile': 'Profile',
    'darkMode': 'Dark mode',
    'themeSystem': 'System',
    'themeLight': 'Light',
    'themeDark': 'Dark',
    'language': 'Language',
    'donate': 'Support the developer',
    'adFreeMode': 'Ad-free for 6 hours',
    'premium': 'Premium',
    'logout': 'Log out',
    'deleteAccount': 'Delete account',
    'logoutConfirm': 'Are you sure you want to log out?',
    'deleteAccountConfirm': 'This action is irreversible. All your data will be deleted and you will lose your Premium benefit if you purchased it. Continue?',
    'aboutApp': 'About Hivefi',
    'appVersion': 'Version 2.0.0',
    'madeBy': 'Developed by',
    'saveName': 'SAVE NAME',
    'nameEmpty': 'Name cannot be empty.',
    'nameUpdated': 'Name updated successfully.',
    'changePassword': 'Change password',
    'changePasswordDesc': 'We will send an email to your registered address with a link to change your password.',
    'sendResetEmail': 'SEND RESET EMAIL',
    'resetSent': 'Email sent. Check your inbox.',
    'email': 'EMAIL',
    'emailHint': 'example@email.com',
    'password': 'PASSWORD',
    'login': 'LOG IN',
    'forgotPassword': 'Forgot your password?',
    'noAccount': 'Don\'t have an account?',
    'register': 'Sign up',
    'tagline': 'Your finances, organized.',
    'name': 'NAME',
    'nameHint': 'Your name',
    'confirmPassword': 'CONFIRM PASSWORD',
    'createAccount': 'CREATE ACCOUNT',
    'alreadyHaveAccount': 'Already have an account?',
    'loginLink': 'Log in',
    'passwordMismatch': 'Passwords do not match.',
    'passwordTooShort': 'Password must be at least 6 characters.',
	'apoyoTitulo': 'Support the developer',
'apoyoSubtitulo': 'Hive-Fi is built by a single person. Your support helps keep improving the app.',
'apoyoCafe': 'A coffee',
'apoyoCafeDesc': 'The fuel of development.',
'apoyoComida': 'A meal',
'apoyoComidaDesc': 'To keep building with energy.',
'apoyoBanquete': 'The full banquet',
'apoyoBanqueteDesc': 'Your most generous support.',
'apoyoNota': 'Contributions do not grant additional benefits in the app.',
'apoyoError': 'Could not process the payment. Please try again.',
'rateApp': 'Rate application',
  'shareApp': 'Share with friends',
  'shareMessage': 'Download Hivefi from the Play Store:',

    // Premium
    'premiumSubtitulo': 'One-time payment. No subscriptions.',
    'premiumBeneficio1': 'Dark mode',
    'premiumBeneficio1Desc': 'Easy on the eyes with a dark theme.',
    'premiumBeneficio2': 'Unlimited categories',
    'premiumBeneficio2Desc': 'Create as many envelopes as you need.',
    'premiumBeneficio3': 'No ads forever',
    'premiumBeneficio3Desc': 'Clean experience without interruptions.',
    'premiumPagoUnico': 'One-time payment — lifetime access',
    'premiumActivar': 'Activate Premium',
    'premiumActivo': 'Premium active',
    'premiumRestaurar': 'Restore previous purchase',
    'premiumRestaurado': 'Purchase restored successfully.',
    'premiumErrorCompra': 'Could not complete purchase. Please try again.',

    // Categorías y Sobres
    'newCategory': 'NEW\nCATEGORY',
    'categories_title': 'Categories',
    'your_envelopes': 'Your envelopes',
    'organize_your_money': 'Organize your money in categories.',
    'incomes': 'Incomes',
    'expenses': 'Expenses',
    'no_categories_yet': 'No categories yet.',
    'tap_plus_to_create': 'Tap + to create one.',
    'search_category': 'Search category...',
    'cannot_delete_category_with_money': 'Cannot delete: the category has money assigned.',
    'use_savings': 'Use savings',
    'delete_category': 'Delete category',
    'confirm_delete_category': 'Are you sure you want to delete this category?',
    'edit_name': 'Edit name',
    'new_name': 'New name',
    'save': 'Save',
    'where_to_send_savings': 'Which expense envelope do you want to send the money to?',
    'no_expense_categories': 'You have no expense categories created.',
    'select_envelope': 'Select an envelope',
    'category_already_exists': 'A category with this name already exists.',
    'error_creating_category': 'Error creating category.',
    'type': 'Type',
    'example_category_name': 'Ex: Salary, Food, Travel...',
    'savings_goal_optional': 'Savings goal (optional)',
    'example_amount': 'Ex: 1,000,000',
    'create_category': 'CREATE CATEGORY',
	'new_category': 'New category',
	'incomem': 'Income',

    // Ingresos
    'registerIncome': 'REGISTER\nINCOME',
    'whereMoneyEnters': 'WHICH ACCOUNT RECEIVES THE MONEY?',
    'incomeAmount': 'INCOME AMOUNT',
    'confirmIncome': 'CONFIRM INCOME',
    'incomeRegistered': 'Income registered successfully.',
    'recentHistory': 'RECENT HISTORY',
    'noIncomeCategories': 'No income categories.',
    'createInCategoriesFirst': 'Create one in Categories first.',
    'title_incomes': 'Incomes',
    'income_envelopes_title': 'Income envelopes',
    'income_envelopes_desc': 'Money available to distribute.',
    'search_category_hint': 'Search category...',
    'no_movements_yet': 'No movements yet.',
    'cannot_edit_destined_income': 'Cannot edit: this income has already been allocated.',
    'register_income_title': 'Register income',
    'which_account_money_enters': 'Which account does the money enter?',
    'loading_categories': 'Loading categories...',
    'select_category_hint': 'Select a category',
    'income_amount_label': 'Income amount',
    'error_select_category': 'Select a category.',
    'error_registering_income': 'Error registering income.',
    'confirm_income': 'Confirm income',
    'edit_income_title': 'Edit income',
    'new_amount_label': 'New amount',
    'error_editing_income': 'Error editing income.',
    'save_changes': 'Save changes',

    // Gastos
    'registerExpense': 'REGISTER\nEXPENSE',
    'whereMoneyLeaves': 'WHICH ENVELOPE COVERS THIS EXPENSE?',
    'expenseAmount': 'AMOUNT TO SPEND',
    'confirmExpense': 'CONFIRM EXPENSE',
    'expenseRegistered': 'Expense registered successfully.',
    'notEnoughFunds': 'Not enough money in this envelope.',
    'title_expenses': 'Expenses',
    'expense_envelopes_title': 'Expense envelopes',
    'expense_envelopes_desc': 'You can only spend allocated money.',
    'search_envelope_hint': 'Search envelope...',
    'no_funds': 'No funds',
    'delete_expense_title': 'Delete expense',
    'delete_expense_desc_1': 'The expense will be deleted and',
    'delete_expense_desc_2': 'will be returned to the envelope.',
    'cancel_button': 'Cancel',
    'delete_button': 'Delete',
    'error_select_envelope': 'Select an envelope.',
    'error_registering_expense': 'Error registering the expense.',
    'register_expense_title': 'Register expense',
    'from_which_envelope': 'From which envelope does the money come?',
    'no_envelopes_available': 'You have no envelopes with available money. Allocate money first.',
    'select_envelope_hint': 'Select an envelope',
    'available_label': 'Available',
    'amount_to_spend_label': 'Amount to spend',
    'confirm_expense': 'Confirm expense',
    'error_amount_exceeds_limit': 'The amount exceeds the envelope limit. Maximum:',
    'error_editing_expense': 'Error editing the expense.',
    'edit_expense_title': 'Edit expense',
    'envelope_label': 'Envelope',
    'which_account_money_exits': 'Wich account money exits?',
	'expense_amount_label': 'Amount of expense',
	'delete': 'Delete',
'delete_expense_confirm': 'Delete this expense? The amount will be returned to the envelope.',
	
    // Destinar y Reparto
    'allocateMoney': 'ALLOCATE\nMONEY',
    'allocateSubtitle': 'Distribute your income into spending or savings envelopes.',
    'whereMoneyFrom': 'WHERE DOES THE MONEY COME FROM?',
    'whereMoneyTo': 'WHICH ENVELOPE DO YOU ASSIGN IT TO?',
    'amountToAllocate': 'AMOUNT TO ALLOCATE',
    'confirmAllocate': 'CONFIRM ALLOCATION',
    'allocateRegistered': 'Money allocated successfully.',
    'sameAccountError': 'Origin and destination cannot be the same.',
    'notEnoughFundsGeneral': 'Not enough money available.',
    'savingsLabel': 'SAVINGS',
    'allocate_money_title': 'Allocate money',
    'no_available_money': 'No money available',
    'register_income_first': 'Register an income first to allocate money.',
    'distribute_your_money': 'Distribute your money',
    'assign_money_to_envelopes': 'Assign your money to expense or savings envelopes.',
    'all_incomes': 'All incomes',
    'expense_envelopes': 'Expense envelopes',
    'savings_envelopes': 'Savings envelopes',
    'search_envelope': 'Search envelope...',
    'enter_an_amount': 'Enter an amount.',
    'invalid_amount': 'The amount is invalid.',
    'insufficient_income': 'Not enough income. Available:',
    'error_editing_destination': 'Error editing destination.',
    'edit_destination': 'Edit destination',
    'new_amount': 'New amount',
    'allocate_money': 'Allocate money',
    'where_does_money_come_from': 'Where does the money come from?',
    'no_incomes_available': 'You have no incomes with available money.',
    'select_income': 'Select income',
    'which_envelope_assign': 'Which envelope do you assign it to?',
    'no_expense_savings_envelopes': 'You have no expense or savings envelopes created.',
    'select_destination': 'Select destination',
    'amount_to_allocate': 'Amount to allocate',
    'select_source_of_money': 'Select where the money comes from.',
    'select_destination_of_money': 'Select where the money goes.',
    'insufficient_money': 'Not enough money. Available:',
    'error_allocating_money': 'Error allocating money.',
    'confirm_allocation': 'Confirm allocation',
    'reparto_title': 'Split',
    'no_envelopes_created': 'No envelopes created',
    'create_categories_first': 'Create expense or savings categories first.',
    'move_money_between_envelopes': 'Move money between envelopes',
    'reassign_money_desc': 'Reassign money between your expense and savings envelopes.',
    'savings_envelopes_title': 'Savings envelopes',
    'in_progress': 'In progress',
    'are_you_sure': 'Are you sure?',
    'saving_meta_warning_part1': 'This savings envelope has not reached its goal yet. If you move',
    'saving_meta_warning_part2': 'you will reduce the money allocated to that savings. Do you want to continue?',
    'error_performing_split': 'Error performing the transfer.',
    'move_money_title': 'Move money',
    'reassign_money_short_desc': 'Reassign money between your envelopes.',
    'from_which_envelope_question': 'From which envelope do you take the money?',
    'select_source_hint': 'Select the source',
    'to_which_envelope_question': 'Which envelope do you send it to?',
    'select_destination_hint': 'Select the destination',
    'amount_to_move': 'Amount to move',
    'confirm_split_button': 'Confirm transfer',

    // Historial y Tooltips
    'historialTitle': 'ACCOUNT\nANALYSIS',
    'filterByMonth': 'FILTER BY MONTH',
    'year': 'YEAR',
    'tabSummary': 'SUMMARY',
    'tabIncome': 'INCOME',
    'tabExpenses': 'EXPENSES',
    'balance': 'BALANCE',
    'noMovements': 'No movements.',
    'editMovement': 'Edit movement',
    'cancelMovement': 'Cancel movement',
    'longPressHint': 'Long press a movement to edit or cancel it.',
    'adFreeActivated': 'Ad-free for 6 hours. Enjoy!',
    'adFreeError': 'Could not activate. Please try again.',
    'historialAppBar': 'History',
    'resumenIngresos': 'Income',
    'resumenGastos': 'Expenses',
    'resumenSaldo': 'Balance',
    'donutTitulo': 'Where did I spend most?',
    'donutSinGastos': 'No expenses recorded this month.',
    'otrosLabel': 'Others',
    'sinNombre': 'No name',
    'tendenciaTitulo': 'Income vs Expenses',
    'topSobresTitulo': 'Most active envelopes',
    'topSobresSinGastos': 'No expenses recorded this month.',
    'progresoAhorrosTitulo': 'Savings progress',
    'movimientosTitulo': 'Movements',
    'sinMovimientosMes': 'No movements this month.',
    'tooltip_ingreso': 'Here you register the money you receive. Select an account and confirm the amount.',
    'tooltip_gasto': 'Here you register your expenses. Money is deducted from the selected envelope.',
    'tooltip_destinar': 'Move money from your income into a spending or savings envelope.',
    'tooltip_reparto': 'Redistribute money between your envelopes without needing a new income.',
    'tooltip_categorias': 'Your budget envelopes. You can create income, expense and savings envelopes.',
    'tooltip_historial': 'View and analyze all your transactions filtered by month.',
    'emptyAmount': 'Enter an amount.',
    'invalidAmount': 'The amount is not valid.',
	'deMeta': 'of {meta}',
	'mes_1': 'January',
'mes_2': 'February',
'mes_3': 'March',
'mes_4': 'April',
'mes_5': 'May',
'mes_6': 'June',
'mes_7': 'July',
'mes_8': 'August',
'mes_9': 'September',
'mes_10': 'October',
'mes_11': 'November',
'mes_12': 'December',

  },
};
