name: Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: 'stable'

      - name: Recrear entorno nativo limpio
        run: flutter create --org com.jplabs --project-name hivefi . --platforms=android

      - name: Configurar Gradle para Firebase y minSdk 23
        run: python3 .github/scripts/patch.py

      - name: Verificar build.gradle
        run: cat android/app/build.gradle.kts

      - name: Agregar permiso de Billing
        run: |
          sed -i '/<application/i \    <uses-permission android:name="com.android.vending.BILLING" />' android/app/src/main/AndroidManifest.xml

      - name: Decodificar Keystore y crear key.properties
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=%s\nstoreFile=upload-keystore.jks\n' \
            '${{ secrets.STORE_PASSWORD }}' \
            '${{ secrets.KEY_PASSWORD }}' \
            '${{ secrets.KEY_ALIAS }}' \
            > android/key.properties

      - name: Verificar key.properties
        run: cat android/key.properties

      - name: Crear google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - run: flutter pub get

      - name: Generar icono de launcher
        run: dart run flutter_launcher_icons

      - name: Compilar APK y AAB
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: hivefi-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Subir AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: hivefi-aab
          path: build/app/outputs/bundle/release/app-release.aab